### ISSUE TITLE
Can you help me

### ISSUE THREAD

**Issue by vutbaza** [jardiamj/BYOWS_RPi#2]
Can you make file BYOWS_RPi for upload data to Weather Underground ?
I tried many times to follow this project . I don't understand why i can't do it.
https://projects.raspberrypi.org/en/projects/uploading-weather-data-to-weather-underground

sorry for my english

**Comment by jardiamj** [comment]
weeWX has a built-in service to upload data to Weather Underground, you just need to enable and provide your credentials in the weewx.conf file.
The documentation is here: http://www.weewx.com/docs/usersguide.htm

**Comment by jardiamj** [comment]
What exactly are you having trouble with? Can you point to a specific point in that guide where you are getting stuck?

**Comment by AvEloHell** [comment]
now all works well
I couldn’t have done it without you. Thank you
