### ISSUE TITLE
Unable to disable simulator drive

### ISSUE THREAD

**Issue by seesix** [jardiamj/BYOWS_RPi#6]
I have installed the byows driver on the latest version of weewx running buster on pi3b.

I have restarted the weewx service but when i load the web gui 

http://localhost/weewx

It displays data from the simulator driver.

List Drivers returns
=====================================
pi@weatherpi:~ $  wee_config --list-drivers
Module name              Driver name    Version  Status                   
  user.byows_rpi           BYOWS          0.51                              
  weewx.drivers.acurite    ?              ?        No module named 'usb'    
  weewx.drivers.cc3000     ?              ?        No module named 'serial' 
  weewx.drivers.fousb      ?              ?        No module named 'usb'    
  weewx.drivers.simulator  Simulator      3.2                               
  weewx.drivers.te923      ?              ?        No module named 'usb'    
  weewx.drivers.ultimeter  ?              ?        No module named 'serial' 
  weewx.drivers.vantage    Vantage        3.2.0                             
  weewx.drivers.wmr100     ?              ?        No module named 'usb'    
  weewx.drivers.wmr200     ?              ?        No module named 'usb'    
  weewx.drivers.wmr300     ?              ?        No module named 'usb'    
  weewx.drivers.wmr9x8     ?              ?        No module named 'serial' 
  weewx.drivers.ws1        WS1            0.40                              
  weewx.drivers.ws23xx     WS23xx         0.41                              
  weewx.drivers.ws28xx     ?              ?        No module named 'usb'  
===========================================

Is there something  else  i need to do?

**Comment by seesix** [comment]
this is from my weewx.conf

##############################################################################

#   This section binds a data store to a database.

[DataBindings]

    [[wx_binding]]
        # The database must match one of the sections in [Databases].
        # This is likely to be the only option you would want to change.
        database = weather
        # The name of the table within the database
        table_name = WEATHER_MEASUREMENT
        # The manager handles aggregation of data for historical summaries
        manager = weewx.manager.DaySummaryManager
        # The schema defines the structure of the database.
        # It is *only* used when the database is created.
        schema = schemas.wview_extended.schema
        #schemas.wview.schemaschema = schemas.wview.schema
##############################################################################

#   This section defines various databases.

[Databases]

    # A SQLite database is simply a single file
 #   [[archive_sqlite]]
 #       database_name = weewx.sdb
 #       database_type = SQLite

    # MySQL
    [[archive_mysql]]
        database_name = weather
        database_type = MySQL
        user = [USER]
        password = [password]
        driver = weedb.mysql

##############################################################################

**Comment by randallgray** [comment]
seesix,
In your weewx.conf file make sure to specify your new driver in the following places...

Under the *[Station]* section edit the station_type line to read:
*station_type = BYOWS* 

...and add a *new* section at the bottom of the file to read:
*[BYOWS]
    driver = user.byows_rpi*

Now stop/restart WeeWX and refresh your web page.  You might have to give
it up to 5 minutes or so to generate new data and present it to the web server.

Things to note:
-- The station type value (BYOWS in this case) MUST match exactly the new section name you add.
-- "byows_rpi" should be the name of your driver file minus the extension.
-- The *user.* prefix indicates the file resides in /home/weewx/bin/user.
You could copy it to the "drivers" directory but this is overwritten during
upgrades -- best to put it in bin/user.

And one more thing, while the "driver" line is required, you can also add
optional lines to set values for your driver.  For example,
you can set values for your BME280 module (if you have one) -- so
underneath the *driver=* line you would add something like:

bme280_port = 1
bme280_address = 0x77

If these are duplicates of lines in the driver, they will overwrite values
set in the driver file.  Some find this more convenient than editing the driver
itself. You can add as many of these optional lines as you want...

Good luck.

Randall Gray
