### ISSUE TITLE
Wind Gust?

### ISSUE THREAD

**Issue by SvenTaveby** [jardiamj/BYOWS_RPi#9]
Hi
Wind gust is left to weewx to handle (=average 5 minutes).
I don't know if I can get this into Your excellent driver  by myself.
https://projects.raspberrypi.org/en/projects/build-your-own-weather-station/6 has a way.
Suggestions?

/Sven

**Comment by randallgray** [comment]
That's right, WeeWX calculates wind gust.  Look through the documentation,
the steps to add this chart to your site are spelled out here.
--Randall Gray

**Comment by SvenTaveby** [comment]
Hi
Yes, I got the graph. But Weewx uses average for last archive interval (default 5mins). And this version of  byows doesn't store gust values I think. So that is what I'd like to add.

**Comment by jardiamj** [comment]
Hi!

Sorry for the late reply, I decided to go back to studying Software
Engineering and work + school are keeping extremely busy these days.

I remember asking, when I was writing the driver, if calculating wind gust
in it was a good idea or not. The following was Tom's response (which I
found in an old email):

"Generally, drivers should not calculate derived variables. They should let
StdWXService do that. It has access to way more information than the
driver, particularly the database. This allows it to do things like correct
for semi-diurnal tides."

This is the reason why the driver doesn't calculate wind gust.

Jardi.

**Comment by SvenTaveby** [comment]
Hi
Brilliant. 
So my theory about a gust = average 5 minutes is correct? 
We often have wind gusts that make the house shiver, but the weather station says "gust 5 m/s". 
Because the gust is more like 30seconds. 
I'll see if I tinker with the driver, or just iterate every minute.
And thank You for writing the driver in the first place - You do have som users around the globe!

Have a nice weekend!
/Sven
